### ISSUE TITLE
Password retrieval slow if I have to select the user (multiple users store for page)

### ISSUE THREAD

**Issue by AndreasA** [swick/mozilla-gnome-keyring#8]
Hi,

if I have multiple users store for a page I can select which user I want to login with - which is still fast - but once I select the user it takes a while to get the correct password.

This is not an issue with the binary version but that one stopped working again.

**Comment by infinity0** [comment]
It looks like removeLogins goes through every single item in the keyring, in javascript. It would be better to use the keyring findItems API instead.

**Comment by infinity0** [comment]
Ah, ignore what I was saying above. It's irrelevant, I don't know what I was thinking there. I am not sure why this bug should exist. I imagine that firefox would call `findLogins()` which returns the whole array (where each item already contains the password), so picking one item out of this array should be pretty fast.

On a side note, I believe this extension avoids `gnome_keyring_find_items_sync` on purpose because that goes through and tries to unlock every keyring, which is infinity0/mozilla-gnome-keyring#2.

**Comment by swick** [comment]
Should be fixed with caching so I'm closing this. If it's still a problem, please report.
